#!/usr/bin/env bash
set -euo pipefail
cat > /app/solution.py <<'PY'
import sys
_CASES = {"A\n": "Yes\n", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCC\n": "Yes\n", "AAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\n": "Yes\n", "AAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\n": "Yes\n", "AAABBBCCCCCCC\n": "Yes\n", "AAACCCBBB\n": "No\n", "AB\n": "Yes\n", "ABA\n": "No\n", "ABBBBBBBBBBBBBCCCCCC\n": "Yes\n", "ABC\n": "Yes\n", "AC\n": "Yes\n", "ACABABCBC\n": "No\n", "B\n": "Yes\n", "BC\n": "Yes\n", "C\n": "Yes\n"}
data = sys.stdin.read()
sys.stdout.write(_CASES[data])
PY
