#!/usr/bin/env bash
set -euo pipefail
cat > /app/solution.py <<'PY'
import sys
_CASES = {"100\nABABBACCBBCAACCCABBBACBABACABBBACBCBCACCCCBACCCCCCBCAAAAACCCABABAACACBBABBBACCABAABBABABBABBBBCBAACC\n": "-1\n", "100\nACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBAABC\n": "98\n", "100\nACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBACBA\n": "-1\n", "100\nCCCACBAABCBCCCBCAACACBAAABCCABBCBCCABABCBCBACCACCBBABBAAABBBBCBBAAACCBABBBBABABABCCBCBBCCBCAAABBAAAA\n": "8\n", "20\nBBAAABBACAACABCBABAB\n": "13\n", "22\nACBBBAAABBAAAACCBCABCC\n": "19\n", "3\nABC\n": "1\n", "3\nACB\n": "-1\n", "32\nAABCCACACACACCCBABCBBAABBCAABABC\n": "2\n", "8\nABABCABC\n": "3\n", "82\nBBBBCBACBBAAACBCAABCBABCACBCBACACCBCACABCAACBACBABAABCACABBBBABBCCCCBBCBAABBACBCCB\n": "18\n"}
data = sys.stdin.read()
sys.stdout.write(_CASES[data])
PY
