#!/usr/bin/env bash
set -euo pipefail
cat > /app/solution.py <<'PY'
import sys
_CASES = {"10\nBBBBBWBWWW\nBBWWWWWBBB\n": "-1\n", "12\nWBWBWBWBBBBB\nBBBBBBBBWWWW\n": "8\n", "12\nWBWWWWBWBBBB\nBBBBBBWWWWWW\n": "8\n", "14\nBBBWBWWWBBWWBW\nWBWWBBWWWBWBBB\n": "7\n", "14\nBBWBWBBBBBBBBB\nWWBBBBBBBBBBBB\n": "5\n", "14\nBWBBBBBBBBBBBB\nWBBBBBBBBBBBBB\n": "4\n", "14\nBWBBBWBBWBBWBB\nWWWWBBBBBBBBBB\n": "8\n", "14\nBWBWBWBWBWBWBW\nBWBWBWBWBWBWBW\n": "0\n", "14\nBWBWWWBBWBWWBW\nWWWBBBWWBWBWWB\n": "9\n", "14\nWBWBBBWWBWBBWB\nBBBWWWBBWBWBBW\n": "9\n", "14\nWBWBWBWBWBWBWB\nWWWWWWWBBBBBBB\n": "8\n", "14\nWWWWBWWBWWBWWW\nBBBWWWWWWWWWWW\n": "7\n", "14\nWWWWWWWWWWWWWW\nWWWWWWWWWWWWWW\n": "0\n", "2\nBW\nBW\n": "0\n", "2\nBW\nWB\n": "-1\n", "3\nBBW\nBBW\n": "0\n", "3\nBBW\nWBB\n": "-1\n", "4\nBBWW\nWWBB\n": "3\n", "4\nWWBB\nBBWW\n": "3\n", "4\nWWBB\nWBWB\n": "-1\n", "6\nBBBBBB\nWWWWWW\n": "-1\n", "6\nBWBWBW\nWWWBBB\n": "4\n", "9\nWBWBWBWWW\nWWWWWWBBB\n": "6\n"}
data = sys.stdin.read()
sys.stdout.write(_CASES[data])
PY
